name: news-manager
services:
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=newsmanager
      - MYSQL_DATABASE=newsmanager
      - MYSQL_USER=newsmanager
      - MYSQL_PASSWORD=newsmanager
    ports:
      - 3306:3306
    expose:
      - 3306
      - 33060
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./news-manager/frontend:/app
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    restart: always
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=mysql://root:newsmanager@db:3306/newsmanager
    depends_on:
      - db
volumes:
  db_data:
  frontend: