version: '3.3'

name: news-manager
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/noticias
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    restart: always
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060
volumes:
  db_data:
  - /home/andyarm/gitapps/news-manager/frontend:/app/frontend
  - /home/andyarm/gitapps/news-manager/backend:/app/backend